volumes:
  foodgram_db_data:
  static:
  media:

services:

  db:
    image: postgres:14.20
    env_file: .env
    volumes:
      - foodgram_db_data:/var/lib/postgresql/data
  backend:
    build: ./foodgram/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    build: ./nginx/
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80

