# Generated by Django 5.2.8 on 2025-12-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/self.pk', verbose_name='Аватар'),
        ),
    ]
