# Generated by Django 5.2.8 on 2025-12-16 17:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=users.models.avatar_file_name, verbose_name='Аватар'),
        ),
    ]
