# Generated by Django 5.2.8 on 2026-01-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_ingredient_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
