# Generated by Django 5.2.8 on 2025-12-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
