# Generated by Django 5.2.8 on 2025-12-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_recipeingredient_options_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
    ]
