# Generated by Django 5.2.8 on 2025-12-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_ingredient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10, unique=True, verbose_name='Короткая ссылка на рецепт')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='social.recipe', verbose_name='Рецепт')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'slug'), name='unique_short_link')],
            },
        ),
    ]
