# Generated by Django 5.2.8 on 2025-12-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_recipeshorturl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeshorturl',
            options={'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
    ]
